# Site settings
author: Jake Sleman
title: Jake's Blog
header-img: img/home-bg.png
email: jakesleman@icloud.com
copyright_name: Jake Sleman
description: > # this means to ignore newlines until "baseurl:"
  Software Development 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  jakesleman

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
